version: "3"

services:

  luminesce-sdk-python-test:
    build: .
    container_name: luminesce-sdk-python-preview-test
    image: finbourne/luminesce-sdk-python-preview-test
    environment:
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_PASSWORD
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PROXY_ADDRESS
      - FBN_PROXY_USERNAME
      - FBN_PROXY_PASSWORD
      - FBN_LUMI_API_URL=${FBN_BASE_API_URL}/honeycomb
      - FBN_ACCESS_TOKEN=${FBN_ACCESS_TOKEN}
    volumes:
      - .:/usr/src
